include: package:flutter_lints/flutter.yaml

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
  rules:
    - avoid-dynamic
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-moving-to-variable
    - prefer-match-file-name

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/core/l10n/generated/**"
  errors:
    invalid_annotation_target: ignore

# https://dart-lang.github.io/linter/lints/
linter:

  rules:
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_print: true
    annotate_overrides: true
    await_only_futures: true
    camel_case_types: true
    non_constant_identifier_names: true
    empty_statements: true
    empty_catches: true
    file_names: true
    constant_identifier_names: false
    prefer_const_constructors: true
    #    cancel_subscriptions: true
    no_logic_in_create_state: true
    use_build_context_synchronously: false
    #    always_declare_return_types: true
    #    always_put_control_body_on_new_line: true
    #    always_put_required_named_parameters_first: true
    #    always_specify_types: true
    avoid_field_initializers_in_const_classes: true
    #    avoid_multiple_declarations_per_line: true
    avoid_unnecessary_containers: true
    #    avoid_void_async: true
    #    require_trailing_commas: true
    use_decorated_box: true
    use_colored_box: true
    unnecessary_to_list_in_spreads: true
    empty_constructor_bodies: true

# На будущее

# вот это думаю в будущем нужно включить, чтобы использовать только map
#    - avoid_function_literals_in_foreach_calls

# Интересная опция, Use Flutter TODO format: // TODO(username): message, https://URL-to-issue.
# Думаю можно будет включить в будущем
#    - flutter_style_todos
